{{- if .Values.jxBootJobEnvVarSecrets }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    git-operator.jenkins.io/kind: git-operator
  name: jx-boot-job-env-vars
type: Opaque
data:
  {{- range $pkey, $pval := .Values.jxBootJobEnvVarSecrets }}
  {{ $pkey }}: {{ $pval | b64enc }}
  {{- end }}
{{- end -}}
