{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-03T17:30:47Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: upgrade deps
    sha: 3bef5e866ea20d739767b54986fbbf0b02beb69e
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: disable the custom files unless an env var is specified
    sha: 314e11b1f987351695679ef290a23b9533dcb800
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: bring back support for custom boot file names

      whoops - I didn't realise it was still required for Azure
    sha: e0f5e31912a6bb3172a5541f41f777916fda9fe0
  gitHttpUrl: https://github.com/jenkins-x/jx-git-operator
  gitOwner: jenkins-x
  gitRepository: jx-git-operator
  name: '{{ .Chart.Name }}'
  version: 0.0.164
status: {}
 
{{- end }}
