{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-05T10:59:14Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: upgrade go dependencies

      from: https://github.com/jenkins-x/jx3-versions
    sha: 88757d328ad6346cc783b92f7036274b1dcbb0f9
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: just use multi-arch images
    sha: 9681a9acb7fc05b79ab841fa05e5b5364e4d5a49
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: simplify pipelines
    sha: 155a1f324daf9caf7badf71ae6c41a3740f0a192
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: update deps
    sha: 8c18eb9efe301ce75c6b5ec42431bcd8406e66b2
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: avoid including the git user/token in the logs
    sha: 9252dd5b67eeb06515f2650e2ccf8db594e1c74c
  gitHttpUrl: https://github.com/jenkins-x/jx-git-operator
  gitOwner: jenkins-x
  gitRepository: jx-git-operator
  name: '{{ .Chart.Name }}'
  version: 0.0.155
status: {}
 
{{- end }}
