{{- if .Values.url }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    git-operator.jenkins.io/kind: git-operator
  name: jx-boot
type: Opaque
data:
  url: "{{ .Values.url | b64enc }}"
  username: "{{ .Values.username | b64enc }}"
  password: "{{ .Values.password | b64enc }}"
  gitInitCommands: "{{ .Values.gitInitCommands | b64enc }}"
{{- end -}}