image:
  repository: gcr.io/jenkinsxio-labs-private/jx-git-operator
  tag: 0.0.15
  pullPolicy: IfNotPresent

rbac:
  # if enabled lets install a ClusterRole and ClusterRoleBinding otherwise use Role / RoleBinding
  cluster: true

serviceAccount:
  name: "jx-git-operator"
  # a map of annotations to add to the ServiceAccount
  annotations: {}

# define environment variables here as a map of key: value
env: {}

# a map of annotations to add to the pod
podAnnotations: {}

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi